/*Write a multithreaded program that generates the Fibonacci series. The program
should work as follows: The user will enter on the command line the number of
Fibonacci numbers that the program is to generate. The program then will create a
separate thread that will generate the Fibonacci numbers, placing the sequence in
data that is shared by the threads (an array is probably the most convenient data
structure). When the thread finishes execution the parent will output the sequence
generated by the child thread. Because the parent thread cannot begin outputting the
Fibonacci sequence until the child thread finishes, this will require having the parent
thread wait for the child thread to finish.*/

#include <stdio.h>
#include <stdlib.h>  
#include <pthread.h>
#define MAX_NUM 50

unsigned long long fibonacci[MAX_NUM];

// Function to generate Fibonacci numbers in a separate thread; arg=no. of fibo to be generated
void* generateFibonacci(void* arg) {
    int n = *((int*)arg);

    // Initialize the first two Fibonacci numbers
    fibonacci[0] = 0;
    fibonacci[1] = 1;

    for (int i = 2; i < n; i++) {
        fibonacci[i] = fibonacci[i - 1] + fibonacci[i - 2];
    }

    pthread_exit(NULL);//exit once generated
}

int main(int argc, char* argv[]) {
    if (argc != 2) {
        printf("Usage: %s u did not mention the number of fibo series to be Generated in the command line\n", argv[0]);
        return 1;
    }

    int n = atoi(argv[1]);// argv is in string format and we need the integer so we use ASCII to Integer(atoi)

    //this if the number is exceeding
    if (n <= 0 || n > MAX_NUM) {
        printf("Please enter a valid number between 1 and %d\n", MAX_NUM);
        return 1;
    }

    pthread_t tid;
    int thread_arg = n;

    // Create a thread to generate Fibonacci numbers
    //pthread_create(addr of thread var or identifier, thread attributes, start function(where the tread should strt), argument for the srt fxn)
    if (pthread_create(&tid, 0, generateFibonacci, &thread_arg) != 0) {
        perror("pthread_create");
        return 1;
    }
    // wait for the termination of the specified thread (tid).blocks the execution of the calling thread until finishs its exec
    //2nd arguement is the place where the return value of the thread will be stored(here we dont need it so 0)
    if (pthread_join(tid, 0) != 0) {
        perror("pthread_join");
        return 1;
    }

    printf("Generated Fibonacci sequence:\n");
    for (int i = 0; i < n; i++) {
        printf("%llu ", fibonacci[i]);
    }
    printf("\n");
    return 0;
}
